### ISSUE TITLE
sort - by integer

### ISSUE THREAD

**Issue by chaimt** [custom-cards/flex-table-card#43]
I am sorting by the state column that is a string but have an integer value, and the sort is not correct:
195
354
4

**Comment by daringer** [comment]
in order to get a proper sort for a given column you'll have to convert the value to an integer or float, the `modify` key is made for that, please check the documentation, like [this one](https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-simple-cell-formatting.md). If you are sure that you'll always have an integer the issue should be easily solvable using something like 
```
modify: parseInt(x)
```

**Comment by chaimt** [comment]
works like a charm
thanks
