### ISSUE TITLE
column sorting problem

### ISSUE THREAD

**Issue by arifroni** [custom-cards/flex-table-card#44]
hello, I am trying to make a table with some sensors with yearly energy value. but for some reason, the sorting is not working.

[https://imgur.com/2zYJbY9](url)

Also instead of a friendly name of a sensor, is it possible to use a custom name of the sensor?

**Comment by muzzak123** [comment]
Hi ya, Great card. Well done. Not sure if this is the same issue or not as I can't see @arifroni image.
The sorting problem I'm having is with percentages. It is the age old problem where 100% is seen as before 20% because it starts with a 1 and 20% starts with a 2. For example
![Untitled](https://user-images.githubusercontent.com/51472089/108153562-630dcc80-7116-11eb-8716-c0e8ecb24fde.png)
It also happens when I sort by IP Address
![Untitled1](https://user-images.githubusercontent.com/51472089/108153743-bf70ec00-7116-11eb-9755-a9d272b54271.png)

**Comment by arifroni** [comment]
> Hi ya, Great card. Well done. Not sure if this is the same issue or not as I can't see @arifroni image.
> The sorting problem I'm having is with percentages. It is the age old problem where 100% is seen as before 20% because it starts with a 1 and 20% starts with a 2. For example
> ![Untitled](https://user-images.githubusercontent.com/51472089/108153562-630dcc80-7116-11eb-8716-c0e8ecb24fde.png)
> It also happens when I sort by IP Address
> ![Untitled1](https://user-images.githubusercontent.com/51472089/108153743-bf70ec00-7116-11eb-9755-a9d272b54271.png)
> And I'm not sure what is going on when I sort by dBm ?
> ![Untitled2](https://user-images.githubusercontent.com/51472089/108154234-82f1c000-7117-11eb-9413-292791557ec7.png)

you are absolutely right about the sorting procedure. I still haven't found any solution. if you do, please let me know here.

**Comment by muzzak123** [comment]
I think the fix is with @daringer  to modify the code

**Comment by muzzak123** [comment]
hey @arifroni - if your interested I've modified the original js to make it work properly with sorting numbers and IP addresses

**Comment by arifroni** [comment]
@muzzak123 yes please :)

**Comment by muzzak123** [comment]
Here it is - no guarantees or support 😃 
[flex-table-card.js.txt](https://github.com/custom-cards/flex-table-card/files/6008649/flex-table-card.js.txt)
- save this file over the top of the existing one in \config\www\community\flex-table-card\flex-table-card.js (make sure to give it the same name)
- delete the file flex-table-card.js.gz in the same directory
- and then refresh your table in your browser

hopefully that will work

**Comment by daringer** [comment]
Feel free to make this a proper PR so all can use it. 
(sorry, didn't have time to look into it by myself)

**Comment by muzzak123** [comment]
OK - never done that but I'll give it a shot

**Comment by arifroni** [comment]
its sorting the values as it should. nice work @muzzak123 
another question, is it possible to set name to individual entities? i don't want the friendly name to be shown on the table.
![image](https://user-images.githubusercontent.com/59896374/108491037-b3fefb80-72a3-11eb-9313-efcd7b46fdf6.png)

**Comment by muzzak123** [comment]
@daringer Pull request created I think/hope I did it right.

@arifroni Your "friendly" names don't look very friendly. I would suggest you change the friendly names on your entities to what you want, like "Yearly Energy TV" and then show those. After all that's why there called friendly names. 
Also this thread is about your **sorting** issue, so probably not the right place to be asking questions about other things like this.
